name: 'Questions / Help 💬'
description: If you have questions, please check StackOverflow
title: '[Please read the message below]'
labels: ['💬 Question']
body:
  - type: markdown
    attributes:
      value: |
        ## Questions and Help 💬

        This issue tracker is reserved for bug reports and feature proposals.

        For anything else, such as questions or getting help, please see:

        - [React Native](https://reactnative.dev/docs/getting-started)
  - type: checkboxes
    id: no-post
    attributes:
      label: |
        Please do not submit this issue.
      description: |
        :bangbang: &nbsp; This issue will be closed. :bangbang:
      options:
        - label: I understand
          required: true
